### ISSUE TITLE
(process:10): GLib-GObject-WARNING **: 02:15:19.603: value "-1" of type 'gint' is invalid or out of range for property 'width' of type 'gint'

### ISSUE THREAD

**Issue by ghost** [computationalpathologygroup/pythostitcher#5] opened 2024-09-21 00:25 UTC
Hello @dnschouten, I hope you are doing well. 

I get this error when I think pythostitcher is trying to save a high-res stitched image for sol1.

It would be a great help if you could suggest further steps to resolve this issue. Thank you!

Best,
Ritish

` pyvips.error.Error: unable to call crop `

Here is the traceback:

``` (process:10): GLib-GObject-WARNING **: 02:15:19.603: value "-1" of type 'gint' is invalid or out of range for property 'width' of type 'gint'
2024-09-20 20:15:19 Traceback (most recent call last):
2024-09-20 20:15:19   File "/home/user/pythostitcher-0.3.1/src/main.py", line 287, in <module>
2024-09-20 20:15:19     main()
2024-09-20 20:15:19   File "/home/user/pythostitcher-0.3.1/src/main.py", line 267, in main
2024-09-20 20:15:19     run_case(data_dir, save_dir, output_res)
2024-09-20 20:15:19   File "/home/user/pythostitcher-0.3.1/src/main.py", line 241, in run_case
2024-09-20 20:15:19     generate_full_res(parameters=parameters, log=log)
2024-09-20 20:15:19   File "/home/user/pythostitcher-0.3.1/src/pythostitcher_utils/full_resolution.py", line 568, in generate_full_res
2024-09-20 20:15:19     result_image = perform_blending(
2024-09-20 20:15:19   File "/home/user/pythostitcher-0.3.1/src/pythostitcher_utils/gradient_blending.py", line 160, in perform_blending
2024-09-20 20:15:19     tile_mask = result_mask.crop(xstart, ystart, width, height)
2024-09-20 20:15:19   File "/usr/local/lib/python3.9/site-packages/pyvips/vimage.py", line 1347, in call_function
2024-09-20 20:15:19     return pyvips.Operation.call(name, self, *args, **kwargs)
2024-09-20 20:15:19   File "/usr/local/lib/python3.9/site-packages/pyvips/voperation.py", line 305, in call
2024-09-20 20:15:19     raise Error('unable to call {0}'.format(operation_name))
2024-09-20 20:15:19    pyvips.error.Error: unable to call crop
2024-09-20 20:15:19   extract_area: parameter width not set

**Comment by dnschouten** [comment] 2024-09-23 18:11
Hi Ritish, 

It seems that the crop function fails due to a faulty width parameter, which should have been computed a few lines earlier. My best guess is that something's off with the tissue mask for this particular patch in the slide, leading to an error in calculating the required width of the patch. Could you try to run it interactively and print out some values for the `xstart`, `ystart`, `width `and `height `parameters? And perhaps also show me a visualization of both the full tissue mask as well as the mask of the patch where's it failing? 

Best,
Daan

**Comment by ghost** [comment] 2024-09-25 17:49
Hi Daan, sure. I was using the Docker container and now, I am installing all the dependencies to run the scripts locally on the machine. I am currently working on your comment, will post the details as soon as I have them.

Thank you again for your time and support,

Best,
Ritish

**Comment by zaynah91124** [comment] 2024-09-27 14:02
Hello, I am also trying to install all the dependencies to run the scripts locally on the machine. I hope we can reproduce it as soon as possible. If you have any questions, we can communicate together.

**Comment by dnschouten** [comment] 2024-09-27 14:38
Just as a heads-up: under /build in the repo you can find both the Dockerfile (useful to install ASAP/pyvips) and the requirements.txt file. Those should come in handy if you recreate the environment on a local Linux machine (or WSL).

**Comment by ghost** [comment] 2024-09-27 15:02
Hi Daan. I have another quick question for you. When I look at the configuration detection, I see that the pythostitcher is picking up the wrong stitch edge. I used force config .txt file to specify location but it is still not picking up the correct stitching edge. I was wondering if there is a way to manually control the selection of edge. Thank you!

**Comment by zaynah911** [comment] 2024-09-28 18:10
Hello, could you provide the code for obtaining the mask of the pathological image svs file? For some reason, the mask I segmented myself keeps reporting errors. Traceback (most recent call last):File "/home/user/pythostitcher/pythostitcher/src/preprocessing_utils/prepare_data.py", line 46, in load
assert self.raw_mask.valid(), "Loaded mask was not valid"

**Comment by ghost** [comment] 2024-10-01 01:46
Hi @zaynah911, I used MATLAB Image Processing Toolbox to segment the tissue and create a tissue mask. The mask should be a .tiff file. I converted my raw_images from .svs to .tiff format and saved my masks as .tiff multi-res image files.

**Comment by dnschouten** [comment] 2024-10-01 11:03
Hi @rmaram33, the force_config.txt file is indeed the right way to specify the location of the stitch edge. There are 8 options here: "ul", "ur", "ll", "lr", "left", "right", "top", "bottom" where ul refers to upper-left and lr refers to lower right. You should setup the force_config file in such a way that the label refers to the shape of the fragment and the stitch edges are thus **opposite** to this shape. Example: if you specify "bottom" it will interpret that the fragment represents the bottom half and thus should be stitched at the stitch edge at the top. Similarly, for "ul" it will interpret that the fragments represents the upper left quadrant of the full tissue and thus should be stitched on the bottom and right sides of the fragment. If this still doesn't result in the intended stitch edges, could you provide me with some examples of the images such that we can investigate further?

**Comment by zaynah91124** [comment] 2024-10-03 10:06
> Hi @zaynah911, I used MATLAB Image Processing Toolbox to segment the tissue and create a tissue mask. The mask should be a .tiff file. I converted my raw_images from .svs to .tiff format and saved my masks as .tiff multi-res image files.

Hello, I have been able to reproduce the stitching process, and I have a few questions for you. First, the stitching accuracy depends on the high quality mask. Should this mask keep the same high resolution as the svs source file? Second, can the final output generate an ultra-high resolution composite result? I don't know how to generate an svs file with multiple levels of resolution and metadata. Third, the resolution of each fragment I use for stitching is 10,000×10,000. The process of running the source code to generate a stitching is very long. Is there any solution to this?

**Comment by dnschouten** [comment] 2024-10-03 11:30
Hi @zaynah91124, glad to hear you have been able to reproduce the stitching process. Regarding your questions:
- The mask does not need to have the same resolution as the source file. Just ensure that the image metadata encompasses the image resolution of both the image and the mask. PythoStitcher will then automatically perform any resizes where necessary such that it uses the correct mask size.
- PythoStitcher can indeed generate an ultra-high resolution stitched result with the same resolution as the input images. You can adjust the output resolution with the --resolution flag and specify the desired resolution in µm/px. 
- The stitching time will heavily depend on the --resolution value. On my example data, stitching four fragments of ~100k x 100k  into a composite of ~200k x 200k (highest resolution of 0.25 µm/px) took roughly one hour. If you reduce the resolution to something like 8 µm/px this should reduce the stitching time to a few minutes.

**Comment by ghost** [comment] 2024-10-03 14:25
Hi @dnschouten, thank you so much for the information and guidance. We truly appreciate your patience and support. 

The eight options (for force_config) listed in your previous comment were really helpful. I got the stitching at the right edges. 

I also found a way to use the Docker container with my data. I extracted the finest layer from a pyramidal .tiff image (fragment), generated an additional 7 levels by downsampling (a total of 8 levels), and saved it as a **non-tiled** multi-resolution image using ImageMagick [https://imagemagick.org/index.php](url). I did the same to create the corresponding masks. 

Using these images with Docker Container (pulled from Docker Image as shown in ReadMe), the container ran without any errors and saved the stitched high-resolution .tiff images at the desired resolution. (In my case, the resolution is set to 0.5 micron). 


Thank you again for all your time and support,

Best,
Ritish


```
# Bash
# Extract the finest layer 
# Save it as level0.tiff
convert input.tiff[0] level0.tiff

# Generate levels 1 to 7 by scaling down each previous level by 50%
for i in $(seq 1 7); do
    previous_level="level$((i-1)).tiff"
    current_level="level${i}.tiff"
    convert "$previous_level" -resize 50% "$current_level"
done

# Combine all levels into a non-tiled, multi-resolution TIFF image
convert level0.tiff level1.tiff level2.tiff level3.tiff level4.tiff level5.tiff level6.tiff  level7.tiff \
        -compress none -define tiff:rows-per-strip=0 output.tiff
```

**Comment by dnschouten** [comment] 2024-10-04 12:20
Hi Ritish, glad to hear that it's working now! Just for future reference, I believe this could be even more straightforward if you use vips. Since PythoStitcher works with pyvips, I'd assume that doing the conversion with vips ensures that the final image is readable in PythoStitcher. 

`vips tiffsave "/home/input_image.tif" "/home/output_image.tif" --tile --pyramid --compression jpeg --Q 80 --bigtiff`

For now I'll close this issue. If you run into any additional problems, feel free to re-open this or create a new issue if it's a new problem.

**Closed as completed by dnschouten** 2024-10-04 12:20 UTC
