### ISSUE TITLE
 assert data_dir.is_dir(), "provided patient directory doesn't exist"

### ISSUE THREAD

**Issue by sulaimanvesal** [computationalpathologygroup/pythostitcher#2] opened 2023-06-29 16:14 UTC
Hi, 

Followed your instructions but constantly getting the following error (the same folder structure)?

`assert data_dir.is_dir(), "provided patient directory doesn't exist"`

Also this command doesn't work:

`docker run pythostitcher --datadir "~/sample_data/prostate_P000001" --savedir "~/results" --resolution 0.25`

I should have called as following:

`docker run ghcr.io/computationalpathologygroup/pythostitcher --datadir "~/sample_data/prostate_P000001" --savedir "~/results" --resolution 0.25`

**Comment by dnschouten** [comment] 2023-06-30 14:53
Hi Sulaiman, thanks for bringing this to my attention! 

You are right about the name of the container, I will change it in the documentation. 

Regarding the data_dir error, I was able to reproduce this and figured this error occurs because the container cannot access your local data. You can fix it by creating a volume which essentially mounts the data directory to the container:
`docker run -v ~/sample_data/prostate_P000001:~/sample_data/prostate_P000001 ghcr.io/computationalpathologygroup/pythostitcher --datadir "~/sample_data/prostate_P000001" --savedir "~/results" --resolution 0.25`

Please do let me know if you run into any other issues. I personally always run PythoStitcher by attaching the container to a pycharm instance with the latest code, so I haven't thoroughly tested just running the container from the command line. 

Edit: upon further testing I found that there are some file permission errors between the local host and the container. This will result in some errors when trying to write the results back to the local host. I will investigate this further and get back to you.

**Comment by sulaimanvesal** [comment] 2023-06-30 15:44
Thanks @dnschouten for the prompt response. I changed the path to absolute but the same error.

```
docker: Error response from daemon: invalid volume specification: '/home/svesal/sample_data/prostate_P000001:~/sample_data/prostate_P000001': invalid mount config for type "bind": invalid mount path: '~/sample_data/prostate_P000001' mount path must be absolute.
See 'docker run --help'.
```

**Comment by dnschouten** [comment] 2023-06-30 15:51
Have you tried running it as follows?

`docker run -v /home/svesal:/home/svesal ghcr.io/computationalpathologygroup/pythostitcher --datadir "/home/svesal/sample_data/prostate_P000001" --savedir "/home/svesal/results" --resolution 0.25`

I did some further testing and by creating a volume with a higher parent directory (/home/svesal in your case) rather than the sample_data directory you should be able to solve the permission errors with writing the results as well. Just tried it on my local device and the entire container is now running smoothly.

**Comment by sulaimanvesal** [comment] 2023-06-30 17:04
Sorry to bother you again and again. Never had this sort of issue with Docker. 

Your command worked, but now there is problem with permission error to create the results folder. 


```
(base) svesal@pimed01:~$ sudo docker run -v /home/svesal/sample_data/prostate_P000001:/home/svesal/sample_data/prostate_P000001 ghcr.io/computationalpathologygroup/pythostitcher --datadir "/home/svesal/sample_data/prostate_P000001" --savedir "/home/svesal/results" --resolution 0.25
[sudo] password for svesal:
Executing command: --datadir /home/svesal/sample_data/prostate_P000001 --savedir /home/svesal/results --resolution 0.25


Running job with following parameters:
 - Data dir: /home/svesal/sample_data/prostate_P000001
 - Save dir: /home/svesal/results/prostate_P000001
 - Output resolution: 0.25 µm/pixel

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/svesal/results/prostate_P000001'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/pythostitcher-0.3.0/src/main.py", line 238, in <module>
    main()
  File "/home/user/pythostitcher-0.3.0/src/main.py", line 158, in main
    parameters = load_parameter_configuration(data_dir, save_dir, output_res)
  File "/home/user/pythostitcher-0.3.0/src/main.py", line 76, in load_parameter_configuration
    d.mkdir(parents=True)
  File "/usr/local/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/svesal/results'
```

**Comment by dnschouten** [comment] 2023-07-01 08:58
No worries, glad to help out. I did some digging and I believe I know what the problem is as I encountered this earlier as well. The container probably does not have write access to the results folder, despite running it with sudo. Could you check what the permissions of your result folder are? When I use a result folder with rwx permissions for all users I don't receive this error anymore.

**Comment by sulaimanvesal** [comment] 2023-07-05 15:51
No success, would it be a solution if I rebuild locally the Docker rather than pulling?

**Comment by dnschouten** [comment] 2023-07-06 07:35
Ah, upon re-reading your command I noticed that you mount the data directory (/home/svesal/sample_data/prostate_P000001) directly rather than the parent folder of your user (/home/svesal). Your results folder located at /home/svesal/results will then not be included in the mount, resulting in permissions errors. Can you try running it one more time with: 

`docker run -v /home/svesal:/home/svesal ghcr.io/computationalpathologygroup/pythostitcher --datadir "/home/svesal/sample_data/prostate_P000001" --savedir "/home/svesal/results" --resolution 0.25`

I also noticed that the container is using pre-release 0.3.0. I've published a new version based on pre-release 0.3.1, so I'd also recommend pulling this latest version as it includes some bug fixes. If that still throws the same error, you can indeed try to build the Docker locally using the files provided in /build.

**Comment by dnschouten** [comment] 2023-07-13 08:02
@sulaimanvesal Have you had any success with any of the options? If so, please let me know so I can close this issue.

**Comment by sulaimanvesal** [comment] 2023-07-17 05:59
Hi @dnschouten 

Finally, it worked. Thanks for the help. 

Two last questions: 

- is the segmentation masks for quadrant mandatory? may I ask how do you segment the tissues? specially for mrxs file?
- do we need to apply flipping and rotation to quadrants like AutoSticher Matlab?

**Comment by dnschouten** [comment] 2023-07-17 07:55
Glad to hear that you got it working!

Regarding your questions:

- Yes the segmentation mask is mandatory if you want the full resolution reconstruction (0.25 µm/pixel or any resolution you specify as input argument). To obtain the tissue masks I've personally used the algorithm developed by [Bandi et al.](https://pubmed.ncbi.nlm.nih.gov/31871843/), but I've also tried simpler methods and those also work well. Suppose you have a .mrxs file scanned at 0.25 µm/pixel resolution, you could load in the 4.0 µm/pixel level, perform an Otsu threshold with some pre- or postprocessing, upsample to 2.0 µm/pixel and use that as the mask. The mask doesn't need to be of the same resolution level as the input image, PythoStitcher will figure that out automatically. 
- You do need to apply flipping before using PythoStitcher, but rotation is performed automatically. PythoStitcher will try out multiple rotations, identify a handful of potential reconstructions and reconstruct those. After the reconstruction is done you can then just pick the one which looks correct. If the automatic rotation somehow fails, you can always manually specify the current "location" of the fragment in the force_config.txt file. If you have a fragment named fragment1.mrxs which somewhat looks like the upper left part of a circle/ellipse, you would specify in the force_config.txt file: 'fragment1:ul' and do this for each fragment, please see the example file on how to structure this exactly.

**Closed as completed** 2023-07-24 06:49 UTC
